[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "justbases"
authors = [{name = "Anne Mulhern", email = "amulhern@redhat.com"}]
description = "conversion of ints and rationals to any base"
license = "LGPL-2.1-or-later"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering :: Mathematics",
]
urls = {Homepage = "https://github.com/mulkieran/justbases"}
requires-python = ">=3.12"
dynamic = ["version"]

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["justbases"]
platforms = ["Linux"]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "justbases.version.__version__"}

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["B", "F", "PL"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
skip-magic-trailing-comma = true
